import type { Scene } from "@motionforge/schema";

// 16x16 PNG with colored quadrants (TL red, TR green, BL blue, BR yellow),
// generated by a deterministic script. Quadrants make objectFit modes
// visually distinguishable: contain letterboxes, cover crops.
const quadrantsPng =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAIUlEQVR42mP4z8DwHx8mAo4aMAwMIKAfCBjw4lEDhoUBAFfoPd+JcsLjAAAAAElFTkSuQmCC";


// Minimal self-contained Lottie document (the spike's): a teal rounded
// rectangle translating left-to-right while rotating, 60 frames @ 30fps,
// 200x200. Inlined as a data URL so the fixture needs no network.
const lottieRectJson = JSON.stringify({
  v: "5.7.4",
  fr: 30,
  ip: 0,
  op: 60,
  w: 200,
  h: 200,
  nm: "golden",
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: "rect",
      sr: 1,
      ks: {
        o: { a: 0, k: 100 },
        r: {
          a: 1,
          k: [
            { t: 0, s: [0], e: [180], i: { x: [0.5], y: [0.5] }, o: { x: [0.5], y: [0.5] } },
            { t: 60, s: [180] },
          ],
        },
        p: {
          a: 1,
          k: [
            { t: 0, s: [40, 100, 0], e: [160, 100, 0], i: { x: 0.5, y: 0.5 }, o: { x: 0.5, y: 0.5 } },
            { t: 60, s: [160, 100, 0] },
          ],
        },
        a: { a: 0, k: [0, 0, 0] },
        s: { a: 0, k: [100, 100, 100] },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          nm: "group",
          it: [
            { ty: "rc", nm: "box", d: 1, s: { a: 0, k: [60, 60] }, p: { a: 0, k: [0, 0] }, r: { a: 0, k: 8 } },
            { ty: "fl", nm: "fill", c: { a: 0, k: [0.4, 0.96, 0.84, 1] }, o: { a: 0, k: 100 } },
            { ty: "tr", p: { a: 0, k: [0, 0] }, a: { a: 0, k: [0, 0] }, s: { a: 0, k: [100, 100] }, r: { a: 0, k: 0 }, o: { a: 0, k: 100 } },
          ],
        },
      ],
      ip: 0,
      op: 60,
      st: 0,
    },
  ],
});

const lottieRectDataUrl = `data:application/json,${encodeURIComponent(lottieRectJson)}`;

export type ExactGoldenFixture = {
  kind: "exact";
  id: string;
  description: string;
  frame: number;
  scene: Scene;
};

export type ProbeGoldenFixture = {
  kind: "probe";
  id: string;
  description: string;
  frame: number;
  scene: Scene;
  probes: Array<{
    label: string;
    x: number;
    y: number;
    /** When set, the probe scans the row segment [x, toX] and passes if any pixel matches. */
    toX?: number;
    minAlpha?: number;
    notRgb?: [number, number, number];
    /** Inverts the probe: it passes only when NO pixel in the segment matches. */
    absent?: boolean;
  }>;
};

export type GoldenFixture = ExactGoldenFixture | ProbeGoldenFixture;

export const fixtures: GoldenFixture[] = [
  {
    kind: "exact",
    id: "paint-gradient",
    description: "Solid layout box with vertical gradient background.",
    frame: 0,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 1,
      assets: {},
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            width: "100%",
            height: "100%",
            background: "linear-gradient(180deg, #101820 0%, #244f46 100%)",
          },
          children: [],
        },
      ],
    },
  },
  {
    kind: "exact",
    id: "absolute-insets",
    description:
      "Absolute positioning resolves left, right, bottom, height, and padding.",
    frame: 0,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 1,
      assets: {},
      nodes: [
        {
          id: "root",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            width: "100%",
            height: "100%",
            backgroundColor: "#101820",
          },
          children: [
            {
              id: "bar",
              type: "div",
              from: 0,
              duration: 1,
              style: {
                position: "absolute",
                left: 24,
                right: 40,
                bottom: 28,
                height: 48,
                backgroundColor: "#ffd166",
                borderRadius: 8,
              },
              children: [],
            },
          ],
        },
      ],
    },
  },
  {
    kind: "exact",
    id: "opacity-keyframe",
    description: "Numeric keyframes resolve opacity at the requested frame.",
    frame: 15,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 31,
      assets: {},
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 31,
          style: {
            width: "100%",
            height: "100%",
            backgroundColor: "#101820",
          },
          children: [],
        },
        {
          id: "fade-box",
          type: "div",
          from: 0,
          duration: 31,
          style: {
            position: "absolute",
            left: 80,
            top: 45,
            width: 160,
            height: 90,
            backgroundColor: "#ffffff",
            opacity: 0,
          },
          animations: [
            {
              kind: "keyframes",
              property: "opacity",
              frames: [
                { frame: 0, value: 0 },
                { frame: 30, value: 1 },
              ],
            },
          ],
          children: [],
        },
      ],
    },
  },
  {
    kind: "exact",
    id: "flex-centered-box",
    description:
      "Flex layout centers a fixed-size child inside a padded parent.",
    frame: 0,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 1,
      assets: {},
      nodes: [
        {
          id: "root",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            width: "100%",
            height: "100%",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            padding: 20,
            backgroundColor: "#101820",
          },
          children: [
            {
              id: "center",
              type: "div",
              from: 0,
              duration: 1,
              style: {
                width: 80,
                height: 48,
                backgroundColor: "#4ecdc4",
                borderRadius: 6,
              },
              children: [],
            },
          ],
        },
      ],
    },
  },
  {
    kind: "probe",
    id: "text-shadow-presence",
    description: "Text and text shadow render without exact glyph hashing.",
    frame: 12,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 30,
      assets: {},
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 30,
          style: {
            width: "100%",
            height: "100%",
            backgroundColor: "#101820",
          },
          children: [],
        },
        {
          id: "label",
          type: "text",
          text: "Forge",
          from: 0,
          duration: 30,
          style: {
            position: "absolute",
            left: 96,
            top: 70,
            width: 128,
            height: 40,
            fontFamily: "Arial, sans-serif",
            fontSize: 38,
            fontWeight: 800,
            color: "#ffffff",
            textAlign: "center",
            textShadow: "0 4px 8px rgba(0,0,0,0.6)",
          },
          children: [],
        },
      ],
    },
    probes: [
      {
        label: "glyph area is not background",
        x: 160,
        y: 91,
        minAlpha: 255,
        notRgb: [16, 24, 32],
      },
    ],
  },
  {
    kind: "exact",
    id: "color-keyframe-midpoint",
    description:
      "backgroundColor keyframes interpolate in RGBA space (red to blue at the midpoint).",
    frame: 15,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 31,
      assets: {},
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 31,
          style: {
            width: "100%",
            height: "100%",
            backgroundColor: "#101820",
          },
          children: [],
        },
        {
          id: "color-box",
          type: "div",
          from: 0,
          duration: 31,
          style: {
            position: "absolute",
            left: 80,
            top: 45,
            width: 160,
            height: 90,
          },
          animations: [
            {
              kind: "keyframes",
              property: "backgroundColor",
              frames: [
                { frame: 0, value: "#ff0000" },
                { frame: 30, value: "#0000ff" },
              ],
            },
          ],
          children: [],
        },
      ],
    },
  },
  {
    kind: "exact",
    id: "flex-space-between-stretch",
    description:
      "space-between distributes leftover main-axis space; stretch fills the cross axis for unsized children.",
    frame: 0,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 1,
      assets: {},
      nodes: [
        {
          id: "row",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            width: "100%",
            height: "100%",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "stretch",
            padding: 20,
            backgroundColor: "#101820",
          },
          children: [
            {
              id: "stretched",
              type: "div",
              from: 0,
              duration: 1,
              style: { width: 60, backgroundColor: "#ffd166" },
              children: [],
            },
            {
              id: "fixed",
              type: "div",
              from: 0,
              duration: 1,
              style: { width: 60, height: 60, backgroundColor: "#4ecdc4" },
              children: [],
            },
            {
              id: "tail",
              type: "div",
              from: 0,
              duration: 1,
              style: { width: 60, height: 100, backgroundColor: "#ef476f" },
              children: [],
            },
          ],
        },
      ],
    },
  },
  {
    kind: "exact",
    id: "transform-origin-rotate",
    description:
      "transformOrigin moves the rotation pivot away from the box center.",
    frame: 0,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 1,
      assets: {},
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            width: "100%",
            height: "100%",
            backgroundColor: "#101820",
          },
          children: [],
        },
        {
          id: "pivoted",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 120,
            top: 60,
            width: 120,
            height: 40,
            backgroundColor: "#ffd166",
            transform: "rotate(30deg)",
            transformOrigin: "left top",
          },
          children: [],
        },
      ],
    },
  },
  {
    kind: "exact",
    id: "image-object-fit",
    description:
      "img nodes draw resolved image assets: contain letterboxes, cover crops with objectPosition, fill stretches under a borderRadius clip.",
    frame: 0,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 1,
      assets: {
        quadrants: {
          id: "quadrants",
          type: "image",
          src: quadrantsPng,
        },
      },
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            width: "100%",
            height: "100%",
            backgroundColor: "#101820",
          },
          children: [],
        },
        {
          id: "contained",
          type: "img",
          assetId: "quadrants",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 10,
            top: 45,
            width: 90,
            height: 60,
            objectFit: "contain",
          },
          children: [],
        },
        {
          id: "covered",
          type: "img",
          assetId: "quadrants",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 115,
            top: 45,
            width: 90,
            height: 60,
            objectFit: "cover",
            objectPosition: "left top",
          },
          children: [],
        },
        {
          id: "filled-rounded",
          type: "img",
          assetId: "quadrants",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 220,
            top: 45,
            width: 90,
            height: 60,
            objectFit: "fill",
            borderRadius: 16,
          },
          children: [],
        },
      ],
    },
  },
  {
    kind: "exact",
    id: "gradient-multistop-angle",
    description:
      "linear-gradient supports any stop count, deg angles through the box center, and omitted positions distributed evenly.",
    frame: 0,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 1,
      assets: {},
      nodes: [
        {
          id: "angled",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 10,
            top: 10,
            width: 145,
            height: 160,
            background:
              "linear-gradient(135deg, #ff0000 0%, rgba(0, 255, 0, 0.8) 50%, #0000ff 100%)",
          },
          children: [],
        },
        {
          id: "even-stops",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 165,
            top: 10,
            width: 145,
            height: 160,
            background: "linear-gradient(to right, #101820, #ffd166, #101820)",
          },
          children: [],
        },
      ],
    },
  },
  {
    kind: "exact",
    id: "overflow-hidden-clip",
    description:
      "overflow: hidden clips children to the border box, following borderRadius; the sibling without overflow still paints outside.",
    frame: 0,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 1,
      assets: {},
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            width: "100%",
            height: "100%",
            backgroundColor: "#101820",
          },
          children: [],
        },
        {
          id: "clipped",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 20,
            top: 40,
            width: 120,
            height: 100,
            backgroundColor: "#244f46",
            borderRadius: 28,
            overflow: "hidden",
          },
          children: [
            {
              id: "clipped-child",
              type: "div",
              from: 0,
              duration: 1,
              style: {
                position: "absolute",
                left: -30,
                top: -30,
                width: 90,
                height: 90,
                backgroundColor: "#ef476f",
              },
              children: [],
            },
          ],
        },
        {
          id: "unclipped",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 180,
            top: 40,
            width: 120,
            height: 100,
            backgroundColor: "#244f46",
            borderRadius: 28,
          },
          children: [
            {
              id: "unclipped-child",
              type: "div",
              from: 0,
              duration: 1,
              style: {
                position: "absolute",
                left: -30,
                top: -30,
                width: 90,
                height: 90,
                backgroundColor: "#ffd166",
              },
              children: [],
            },
          ],
        },
      ],
    },
  },
  {
    kind: "exact",
    id: "transform-tween-easings",
    description:
      "Transform lists with matching functions tween smoothly; cubic-bezier and spring easings shape the motion. Sampled mid-tween.",
    frame: 8,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 16,
      assets: {},
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 16,
          style: {
            width: "100%",
            height: "100%",
            backgroundColor: "#101820",
          },
          children: [],
        },
        {
          id: "scaling",
          type: "div",
          from: 0,
          duration: 16,
          style: {
            position: "absolute",
            left: 30,
            top: 60,
            width: 60,
            height: 60,
            backgroundColor: "#ffd166",
            borderRadius: 12,
          },
          animations: [
            {
              kind: "keyframes",
              property: "transform",
              frames: [
                { frame: 0, value: "scale(0.5) rotate(0deg)" },
                {
                  frame: 15,
                  value: "scale(1.4) rotate(90deg)",
                  easing: "cubic-bezier(0.42, 0, 0.58, 1)",
                },
              ],
            },
          ],
          children: [],
        },
        {
          id: "sliding",
          type: "div",
          from: 0,
          duration: 16,
          style: {
            position: "absolute",
            left: 130,
            top: 60,
            width: 60,
            height: 60,
            backgroundColor: "#4ecdc4",
            borderRadius: 12,
          },
          animations: [
            {
              kind: "keyframes",
              property: "transform",
              frames: [
                { frame: 0, value: "translate(0px, -40px)" },
                {
                  frame: 15,
                  value: "translate(0px, 40px)",
                  easing: "spring(0.3)",
                },
              ],
            },
          ],
          children: [],
        },
        {
          id: "stepping",
          type: "div",
          from: 0,
          duration: 16,
          style: {
            position: "absolute",
            left: 230,
            top: 60,
            width: 60,
            height: 60,
            backgroundColor: "#ef476f",
            borderRadius: 12,
          },
          animations: [
            {
              kind: "keyframes",
              property: "transform",
              // Mismatched function lists: must hold scale(0.6) until frame 15.
              frames: [
                { frame: 0, value: "scale(0.6)" },
                { frame: 15, value: "rotate(45deg)" },
              ],
            },
          ],
          children: [],
        },
      ],
    },
  },
  {
    kind: "exact",
    id: "text-embedded-font",
    description:
      "Text rendered with a font asset hashes exactly: the embedded font removes system-font platform variance. The asset id is the font-family name.",
    frame: 0,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 1,
      assets: {
        GoldenSans: {
          id: "GoldenSans",
          type: "font",
          // Inter Bold (latin subset), OFL 1.1 — see public/fonts/README.md.
          // Served by the harness dev server; registered at default weight,
          // so the fixture references it without a fontWeight.
          src: "/fonts/inter-700-latin.woff2",
        },
      },
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            width: "100%",
            height: "100%",
            backgroundColor: "#101820",
          },
          children: [],
        },
        {
          id: "title",
          type: "text",
          text: "Forge 0123",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 0,
            top: 60,
            width: "100%",
            height: 60,
            fontFamily: "GoldenSans",
            fontSize: 44,
            color: "#ffd166",
            textAlign: "center",
            letterSpacing: 1,
          },
          children: [],
        },
      ],
    },
  },
  {
    kind: "exact",
    id: "text-stroke-embedded-font",
    description:
      "Stroked text paints the outline before the fill using an embedded font.",
    frame: 0,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 1,
      assets: {
        GoldenSans: {
          id: "GoldenSans",
          type: "font",
          src: "/fonts/inter-700-latin.woff2",
        },
      },
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            width: "100%",
            height: "100%",
            backgroundColor: "#101820",
          },
          children: [],
        },
        {
          id: "title",
          type: "text",
          text: "STROKE",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 0,
            top: 58,
            width: "100%",
            height: 64,
            fontFamily: "GoldenSans",
            fontSize: 44,
            color: "#ffd166",
            textAlign: "center",
            textStroke: "6px #000000",
          },
          children: [],
        },
      ],
    },
  },
  {
    kind: "exact",
    id: "caption-fitted-text-background",
    description:
      "Caption text draws a measured per-line background behind stroked glyphs.",
    frame: 0,
    scene: {
      schemaVersion: 0,
      width: 360,
      height: 220,
      fps: 30,
      duration: 1,
      assets: {
        GoldenSans: {
          id: "GoldenSans",
          type: "font",
          src: "/fonts/inter-700-latin.woff2",
        },
      },
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            width: "100%",
            height: "100%",
            background: "linear-gradient(180deg, #17202a 0%, #244f46 100%)",
          },
          children: [],
        },
        {
          id: "caption",
          type: "text",
          text: "MEASURED\nPILLS",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 0,
            top: 48,
            width: "100%",
            height: 124,
            fontFamily: "GoldenSans",
            fontSize: 42,
            lineHeight: 1.15,
            color: "#ffffff",
            textAlign: "center",
            textStroke: "5px #000000",
            textBackgroundColor: "rgba(255, 209, 102, 0.24)",
            textBackgroundPaddingX: 22,
            textBackgroundPaddingY: 6,
            textBackgroundRadius: 20,
          },
          children: [],
        },
      ],
    },
  },
  {
    kind: "probe",
    id: "multiline-explicit-newline",
    description:
      "Explicit \\n breaks text into lines spaced by lineHeight; italic and letterSpacing apply.",
    frame: 0,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 1,
      assets: {},
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            width: "100%",
            height: "100%",
            backgroundColor: "#101820",
          },
          children: [],
        },
        {
          id: "stacked",
          type: "text",
          text: "LINE ONE\nLINE TWO",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 40,
            top: 30,
            width: 240,
            height: 120,
            fontFamily: "Arial, sans-serif",
            fontSize: 28,
            fontWeight: 700,
            fontStyle: "italic",
            letterSpacing: 2,
            lineHeight: 1.5,
            color: "#ffffff",
          },
          children: [],
        },
      ],
    },
    // Box center y=90, two lines at 1.5 * 28 = 42px pitch -> line centers
    // at y=69 and y=111. Caps-only text keeps both rows clear of descenders.
    probes: [
      {
        label: "first line has glyph pixels",
        x: 40,
        y: 69,
        toX: 280,
        minAlpha: 255,
        notRgb: [16, 24, 32],
      },
      {
        label: "second line has glyph pixels",
        x: 40,
        y: 111,
        toX: 280,
        minAlpha: 255,
        notRgb: [16, 24, 32],
      },
    ],
  },
  {
    kind: "probe",
    id: "multiline-word-wrap",
    description:
      "Text wider than its box wraps by measured word width into multiple lines.",
    frame: 0,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 1,
      assets: {},
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            width: "100%",
            height: "100%",
            backgroundColor: "#101820",
          },
          children: [],
        },
        {
          id: "wrapped",
          type: "text",
          text: "AAAA BBBB",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 100,
            top: 40,
            width: 120,
            height: 100,
            fontFamily: "Arial, sans-serif",
            fontSize: 30,
            fontWeight: 700,
            lineHeight: 1.5,
            color: "#ffffff",
          },
          children: [],
        },
      ],
    },
    // "AAAA BBBB" at 30px bold is ~170px wide, the box is 120px, so it must
    // wrap to two lines at 45px pitch: line centers at y=67.5 and y=112.5.
    probes: [
      {
        label: "wrapped first line has glyph pixels",
        x: 100,
        y: 68,
        toX: 220,
        minAlpha: 255,
        notRgb: [16, 24, 32],
      },
      {
        label: "wrapped second line has glyph pixels",
        x: 100,
        y: 112,
        toX: 220,
        minAlpha: 255,
        notRgb: [16, 24, 32],
      },
    ],
  },
  {
    kind: "probe",
    id: "text-auto-height",
    description:
      "Text without an explicit height gets its intrinsic wrapped height: a top-anchored block starts at `top` instead of centering in the parent, and a bottom-anchored block sits just above `bottom`.",
    frame: 0,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 1,
      assets: {},
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            width: "100%",
            height: "100%",
            backgroundColor: "#101820",
          },
          children: [],
        },
        {
          id: "top-anchored",
          type: "text",
          text: "AAAA BBBB",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 100,
            top: 40,
            width: 120,
            fontFamily: "Arial, sans-serif",
            fontSize: 30,
            fontWeight: 700,
            lineHeight: 1.5,
            color: "#ffffff",
          },
          children: [],
        },
        {
          id: "bottom-anchored",
          type: "text",
          text: "SSSS",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 10,
            bottom: 20,
            width: 80,
            fontFamily: "Arial, sans-serif",
            fontSize: 30,
            fontWeight: 700,
            lineHeight: 1.5,
            color: "#ffffff",
          },
          children: [],
        },
      ],
    },
    // "AAAA BBBB" wraps to two lines in the 120px box; intrinsic height is
    // 2 × 45 = 90, so the box spans y 40..130 with line centers at 62.5 and
    // 107.5. Under the old fill-parent fallback the block centered at y=130
    // (lines at 107.5/152.5). The subtitle is one 45px line anchored above
    // bottom: 20 — box y 115..160, line center 137.5 (previously 80).
    probes: [
      {
        label: "top-anchored first line starts at `top`",
        x: 100,
        y: 62,
        toX: 220,
        minAlpha: 255,
        notRgb: [16, 24, 32],
      },
      {
        label: "top-anchored second line follows at lineHeight pitch",
        x: 100,
        y: 107,
        toX: 220,
        minAlpha: 255,
        notRgb: [16, 24, 32],
      },
      {
        label: "no third-line pixels below the intrinsic box",
        x: 100,
        y: 152,
        toX: 220,
        minAlpha: 255,
        notRgb: [16, 24, 32],
        absent: true,
      },
      {
        label: "bottom-anchored subtitle sits just above `bottom`",
        x: 10,
        y: 137,
        toX: 90,
        minAlpha: 255,
        notRgb: [16, 24, 32],
      },
    ],
  },
  {
    kind: "exact",
    id: "filter-zindex-border-shadow",
    description:
      "zIndex reorders sibling painting (negative behind, positive in front of document order); border strokes inside the box following borderRadius; boxShadow rides the background fill; a grayscale+brightness filter desaturates an img node.",
    frame: 0,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 1,
      assets: {
        quadrants: {
          id: "quadrants",
          type: "image",
          src: quadrantsPng,
        },
      },
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            width: "100%",
            height: "100%",
            backgroundColor: "#101820",
          },
          children: [],
        },
        {
          id: "z-front-despite-order",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 14,
            top: 30,
            width: 70,
            height: 70,
            backgroundColor: "#ef476f",
            zIndex: 2,
          },
          children: [],
        },
        {
          id: "z-default-overlaps",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 44,
            top: 60,
            width: 70,
            height: 70,
            backgroundColor: "#118ab2",
          },
          children: [],
        },
        {
          id: "z-behind-background-sibling",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 30,
            top: 46,
            width: 70,
            height: 70,
            backgroundColor: "#ffd166",
            zIndex: -1,
          },
          children: [],
        },
        {
          id: "bordered-shadowed",
          type: "div",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 140,
            top: 36,
            width: 80,
            height: 56,
            backgroundColor: "#244f46",
            borderRadius: 12,
            border: "4px solid #ffd166",
            boxShadow: "6px 8px 10px rgba(239, 71, 111, 0.9)",
          },
          children: [],
        },
        {
          id: "filtered-image",
          type: "img",
          assetId: "quadrants",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 240,
            top: 36,
            width: 64,
            height: 64,
            objectFit: "fill",
            filter: "grayscale(100%) brightness(140%)",
          },
          children: [],
        },
        {
          id: "unfiltered-image-control",
          type: "img",
          assetId: "quadrants",
          from: 0,
          duration: 1,
          style: {
            position: "absolute",
            left: 240,
            top: 110,
            width: 64,
            height: 64,
            objectFit: "fill",
          },
          children: [],
        },
      ],
    },
  },
  {
    kind: "exact",
    id: "lottie-frame-seek",
    description:
      "A lottie node renders frame-exact: at scene frame 20 the document's rectangle is mid-travel and mid-rotation, drawn under objectFit contain; a second node at 2x rate shows a later animation frame at the same scene frame.",
    frame: 20,
    scene: {
      schemaVersion: 0,
      width: 320,
      height: 180,
      fps: 30,
      duration: 40,
      assets: {
        sticker: {
          id: "sticker",
          type: "lottie",
          src: lottieRectDataUrl,
        },
      },
      nodes: [
        {
          id: "background",
          type: "div",
          from: 0,
          duration: 40,
          style: {
            width: "100%",
            height: "100%",
            backgroundColor: "#101820",
          },
          children: [],
        },
        {
          id: "natural-rate",
          type: "lottie",
          assetId: "sticker",
          from: 0,
          duration: 40,
          style: {
            position: "absolute",
            left: 10,
            top: 20,
            width: 140,
            height: 140,
            objectFit: "contain",
          },
          children: [],
        },
        {
          id: "double-rate",
          type: "lottie",
          assetId: "sticker",
          playbackRate: 2,
          from: 0,
          duration: 40,
          style: {
            position: "absolute",
            left: 170,
            top: 20,
            width: 140,
            height: 140,
            objectFit: "contain",
          },
          children: [],
        },
      ],
    },
  },
];
